
package cn.majingjing.tm.ws.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloApi", targetNamespace = "http://web.ws.tm.majingjing.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloApi {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello1", targetNamespace = "http://web.ws.tm.majingjing.cn/", className = "cn.majingjing.tm.ws.web.Hello1")
    @ResponseWrapper(localName = "hello1Response", targetNamespace = "http://web.ws.tm.majingjing.cn/", className = "cn.majingjing.tm.ws.web.Hello1Response")
    @Action(input = "http://web.ws.tm.majingjing.cn/HelloApi/hello1Request", output = "http://web.ws.tm.majingjing.cn/HelloApi/hello1Response")
    public String hello1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.majingjing.tm.ws.web.HelloBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello2", targetNamespace = "http://web.ws.tm.majingjing.cn/", className = "cn.majingjing.tm.ws.web.Hello2")
    @ResponseWrapper(localName = "hello2Response", targetNamespace = "http://web.ws.tm.majingjing.cn/", className = "cn.majingjing.tm.ws.web.Hello2Response")
    @Action(input = "http://web.ws.tm.majingjing.cn/HelloApi/hello2Request", output = "http://web.ws.tm.majingjing.cn/HelloApi/hello2Response")
    public HelloBean hello2(
        @WebParam(name = "arg0", targetNamespace = "")
        HelloBean arg0);

    /**
     * 
     * @param password
     * @param parameters
     * @param username
     * @return
     *     returns cn.majingjing.tm.ws.web.QueryDataResponse
     */
    @WebMethod
    @WebResult(name = "queryDataResponse", targetNamespace = "http://web.ws.tm.majingjing.cn/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://web.ws.tm.majingjing.cn/HelloApi/queryDataRequest", output = "http://web.ws.tm.majingjing.cn/HelloApi/queryDataResponse")
    public QueryDataResponse queryData(
        @WebParam(name = "queryData", targetNamespace = "http://web.ws.tm.majingjing.cn/", partName = "parameters")
        QueryData parameters,
        @WebParam(name = "PASSWORD", targetNamespace = "http://web.ws.tm.majingjing.cn/", header = true, partName = "PASSWORD")
        String password,
        @WebParam(name = "USERNAME", targetNamespace = "http://web.ws.tm.majingjing.cn/", header = true, partName = "USERNAME")
        String username);

}
