
package cn.majingjing.tm.ws.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloApiService", targetNamespace = "http://web.ws.tm.majingjing.cn/", wsdlLocation = "http://127.0.0.1:8080/ws/HelloWs?wsdl")
public class HelloApiService
    extends Service
{

    private final static URL HELLOAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOAPISERVICE_EXCEPTION;
    private final static QName HELLOAPISERVICE_QNAME = new QName("http://web.ws.tm.majingjing.cn/", "HelloApiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/ws/HelloWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOAPISERVICE_WSDL_LOCATION = url;
        HELLOAPISERVICE_EXCEPTION = e;
    }

    public HelloApiService() {
        super(__getWsdlLocation(), HELLOAPISERVICE_QNAME);
    }

    public HelloApiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOAPISERVICE_QNAME, features);
    }

    public HelloApiService(URL wsdlLocation) {
        super(wsdlLocation, HELLOAPISERVICE_QNAME);
    }

    public HelloApiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOAPISERVICE_QNAME, features);
    }

    public HelloApiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloApiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloApi
     */
    @WebEndpoint(name = "HelloApiPort")
    public HelloApi getHelloApiPort() {
        return super.getPort(new QName("http://web.ws.tm.majingjing.cn/", "HelloApiPort"), HelloApi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloApi
     */
    @WebEndpoint(name = "HelloApiPort")
    public HelloApi getHelloApiPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.ws.tm.majingjing.cn/", "HelloApiPort"), HelloApi.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOAPISERVICE_EXCEPTION!= null) {
            throw HELLOAPISERVICE_EXCEPTION;
        }
        return HELLOAPISERVICE_WSDL_LOCATION;
    }

}
