
package cn.majingjing.tm.blog.webservice.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FilePortImpl", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FilePortImpl {


    /**
     * 
     * @param tmFileBean
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.UploadResponse")
    public String upload(
        @WebParam(name = "tmFileBean", targetNamespace = "")
        TmFileBean tmFileBean);

    /**
     * 
     * @return
     *     returns cn.majingjing.tm.blog.webservice.api.TmFileBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.DownloadResponse")
    public TmFileBean download();

}
