package v6;

import cn.majingjing.tm.blog.webservice.api.HelloPortImpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-09-01T21:25:24.569+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "HelloPortImplService",
                  wsdlLocation = "https://www.majingjing.cn/tmblog/webservice/hellodemo?wsdl",
                  targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/")
public class HelloPortImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://api.webservice.blog.tm.majingjing.cn/", "HelloPortImplService");
    public final static QName HelloPortImplPort = new QName("http://api.webservice.blog.tm.majingjing.cn/", "HelloPortImplPort");
    static {
        URL url = null;
        try {
            url = new URL("https://www.majingjing.cn/tmblog/webservice/hellodemo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloPortImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://www.majingjing.cn/tmblog/webservice/hellodemo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloPortImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloPortImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloPortImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloPortImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloPortImpl
     */
    @WebEndpoint(name = "HelloPortImplPort")
    public cn.majingjing.tm.blog.webservice.api.HelloPortImpl getHelloPortImplPort() {
        return super.getPort(HelloPortImplPort, cn.majingjing.tm.blog.webservice.api.HelloPortImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloPortImpl
     */
    @WebEndpoint(name = "HelloPortImplPort")
    public cn.majingjing.tm.blog.webservice.api.HelloPortImpl getHelloPortImplPort(WebServiceFeature... features) {
        return super.getPort(HelloPortImplPort, HelloPortImpl.class, features);
    }

}
