
package cn.majingjing.tm.blog.webservice.api;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloPortImplService", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", wsdlLocation = "http://www.majingjing.cn:7070/tmblog/webservice/hellodemo?wsdl")
public class HelloPortImplService
    extends Service
{

    private final static URL HELLOPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOPORTIMPLSERVICE_EXCEPTION;
    private final static QName HELLOPORTIMPLSERVICE_QNAME = new QName("http://api.webservice.blog.tm.majingjing.cn/", "HelloPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.majingjing.cn:7070/tmblog/webservice/hellodemo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOPORTIMPLSERVICE_WSDL_LOCATION = url;
        HELLOPORTIMPLSERVICE_EXCEPTION = e;
    }

    public HelloPortImplService() {
        super(__getWsdlLocation(), HELLOPORTIMPLSERVICE_QNAME);
    }

    public HelloPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOPORTIMPLSERVICE_QNAME, features);
    }

    public HelloPortImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOPORTIMPLSERVICE_QNAME);
    }

    public HelloPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOPORTIMPLSERVICE_QNAME, features);
    }

    public HelloPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloPortImpl
     */
    @WebEndpoint(name = "HelloPortImplPort")
    public HelloPortImpl getHelloPortImplPort() {
        return super.getPort(new QName("http://api.webservice.blog.tm.majingjing.cn/", "HelloPortImplPort"), HelloPortImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloPortImpl
     */
    @WebEndpoint(name = "HelloPortImplPort")
    public HelloPortImpl getHelloPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.webservice.blog.tm.majingjing.cn/", "HelloPortImplPort"), HelloPortImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOPORTIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOPORTIMPLSERVICE_EXCEPTION;
        }
        return HELLOPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
