
package cn.majingjing.tm.blog.webservice.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloPortImpl", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloPortImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloStr", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloStr")
    @ResponseWrapper(localName = "helloStrResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloStrResponse")
    public String helloStr(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.majingjing.tm.blog.webservice.api.HelloBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloList", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloList")
    @ResponseWrapper(localName = "helloListResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloListResponse")
    public List<HelloBean> helloList(
            @WebParam(name = "arg0", targetNamespace = "")
                    List<HelloBean> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.majingjing.tm.blog.webservice.api.HelloBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloObject", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloObject")
    @ResponseWrapper(localName = "helloObjectResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloObjectResponse")
    public HelloBean helloObject(
            @WebParam(name = "arg0", targetNamespace = "")
                    HelloBean arg0);

}
