package cn.majingjing.tm.blog.webservice.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * 常用的简单ws服务接口
 *
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-17T16:12:33.547+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", name = "HelloPortImpl")
@XmlSeeAlso({ObjectFactory.class, com.baidu.ObjectFactory.class})
public interface HelloPortImpl {

    /**
     * 基于集合对象的入参和出参
     */
    @WebMethod
    @RequestWrapper(localName = "helloList", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloList")
    @ResponseWrapper(localName = "helloListResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<HelloBean> helloList(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<HelloBean> arg0
    );

    /**
     * 自定义入参和出参名称
     */
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "sendresp", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", partName = "parameters")
    public Sendresp send(
            @WebParam(partName = "parameters", name = "sendreq", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/")
                    Sendreq parameters
    );

    /**
     * 基于集合map对象的入参和出参
     */
    @WebMethod
    @RequestWrapper(localName = "helloMapList", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloMapList")
    @ResponseWrapper(localName = "helloMapListResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloMapListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<HelloMapBean> helloMapList(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<HelloMapBean> arg0
    );

    /**
     * 简单数据类型的入参和出参
     */
    @WebMethod
    @RequestWrapper(localName = "helloStr", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloStr")
    @ResponseWrapper(localName = "helloStrResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloStrResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String helloStr(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    /**
     * 基于对象的入参和出参
     */
    @WebMethod
    @RequestWrapper(localName = "helloObject", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloObject")
    @ResponseWrapper(localName = "helloObjectResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", className = "cn.majingjing.tm.blog.webservice.api.HelloObjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public HelloBean helloObject(
            @WebParam(name = "arg0", targetNamespace = "")
                    HelloBean arg0
    );

    /**
     * 自定义入参和出参名称
     */
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "seeRetuenNameResponse", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/", partName = "parameters")
    public SeeRetuenNameResponse seeRetuenName(
            @WebParam(partName = "parameters", name = "seeRetuenName", targetNamespace = "http://api.webservice.blog.tm.majingjing.cn/")
                    SeeRetuenName parameters
    );
}
