
package br.com.hodielog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapHodieSoap", targetNamespace = "http://hodielog.com.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapHodieSoap {


    /**
     * 
     *                 Get shipments data from the HODIE system
     *             
     * 
     * @param pass
     * @param shipmentDate
     * @param user
     * @return
     *     returns br.com.hodielog.ReturnData
     */
    @WebMethod(action = "http://hodielog.com.br/shipments")
    @WebResult(partName = "return")
    public ReturnData shipments(
            @WebParam(name = "shipmentDate", partName = "shipmentDate")
                    String shipmentDate,
            @WebParam(name = "user", partName = "user")
                    String user,
            @WebParam(name = "pass", partName = "pass")
                    String pass);

}
